apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: default
type: Opaque
data:
    POSTGRES_USER:
    POSTGRES_PASSWORD:
    SECRET_KEY:
    FIRST_SUPERUSER:
    FIRST_SUPERUSER_PASSWORD:
    FIRST_SUPERUSER_USERNAME:
    SMTP_USER:
    SMTP_PASSWORD:
    BOT_PASSWORD: